#!/bin/sh -x
#
# $FreeBSD:
#

# PROVIDE: flexdiscovery
# REQUIRE: NETWORKING SERVERS DAEMON ldconfig resolv

. /etc/rc.subr
name="flexdiscovery"
rcvar=`set_rcvar`
flexdiscovery_chdir="/var/flex/"
command="/var/flex/flex6k-discovery-util-go"
command_args="--REMOTES 192.168.92.4:7777 --LOCALIFIP 192.168.94.1 --LOCALPORT 7788 --LOCALBR 192.168.94.255"
load_rc_config "$name"
: ${flexdiscovery_enable="YES"}
run_rc_command "$1"